"""
TDD Red Phase tests for STORY-005A-03: GET /api/slack/install — Install URL Builder.

6 test functions covering all Gherkin scenarios from STORY-005A-03 §2.1:

Unit tests (3):
  1. State token round-trip — create_slack_state_token + verify_slack_state_token
  2. State token expiry — raises jwt.ExpiredSignatureError when created with now=(past - 301s)
  3. State token tamper — raises jwt.InvalidTokenError (or subclass) when signature is mutated

Integration tests (3):
  4. Authenticated user → 307 redirect to Slack with correct query params
  5. Anonymous user → 401
  6. Location header does NOT contain plaintext user_id ("alice-uuid-fixture")

RED PHASE: All tests fail until Green phase creates:
  - app.core.security: create_slack_state_token, verify_slack_state_token
  - app.models.slack: SlackInstallState
  - app.api.routes.slack_oauth: router (GET /api/slack/install)
  - app.main: router registered (import will produce 404 until then)

FLASHCARDS.md consulted:
  - BUG-20260411: PyJWT module-local _JWT instance — tests must NOT call
    jwt.decode with verify_signature=False (would poison shared global state
    and let tampered tokens through). Tests use the same helpers the production
    code will use; no direct jwt module-level manipulation here.
  - Auth cookies: samesite="lax" — deliberate for OAuth redirect flows (EPIC-005).

ADR compliance:
  - ADR-001: JWT auth via access_token httpOnly cookie, get_current_user_id dep.
  - ADR-021 / ADR-025: 7 scopes (app_mentions:read, channels:history,
    channels:read, chat:write, groups:history, groups:read, im:history).
"""

from __future__ import annotations

import time
import uuid
from urllib.parse import parse_qs, urlparse

import jwt
import pytest
from fastapi.testclient import TestClient

from app.main import app
from app.core.config import settings
from app.core.security import create_access_token

# --- RED PHASE: these imports do NOT exist yet — they drive the failing tests ---
from app.core.security import (  # noqa: F401
    create_slack_state_token,
    verify_slack_state_token,
)
from app.models.slack import SlackInstallState  # noqa: F401
# -------------------------------------------------------------------------------

# The exact 7 Slack OAuth scopes required by ADR-021 + ADR-025
EXPECTED_SCOPES = {
    "app_mentions:read",
    "channels:history",
    "channels:read",
    "chat:write",
    "groups:history",
    "groups:read",
    "im:history",
}


@pytest.fixture
def client() -> TestClient:
    """
    Return a FastAPI TestClient wrapping the main app.

    TestClient uses HTTPX under the hood and does NOT follow redirects by
    default (follow_redirects=False) so we can inspect 307 responses directly.
    """
    return TestClient(app, follow_redirects=False)


@pytest.fixture
def authenticated_client() -> TestClient:
    """
    Return a TestClient pre-loaded with a valid access_token cookie.

    Creates a real JWT signed with the same secret as the production auth
    system, using create_access_token (the existing security helper). The
    user_id is the recognizable "alice-uuid-fixture" UUID-shaped string — this
    lets the "no plaintext user_id in Location" test assert that the literal
    string does not appear in the Slack redirect URL.

    Uses the Authorization header path (secondary path in get_current_user_id)
    rather than setting a raw cookie so we don't depend on cookie jar behavior
    across TestClient instances.
    """
    # Use a fixed UUID so tests can assert on it deterministically.
    # Team Lead fix (2026-04-12): original Red Phase string "a11ce000-f1x7-0000-0000-a11ce0fixture"
    # was not a valid UUID (non-hex chars + wrong length). Replaced with a valid
    # hex-only UUID that preserves the "a11ce0" motif for recognition.
    alice_uuid = uuid.UUID("a11ce000-0000-0000-0000-a11ce0000001")
    token = create_access_token(alice_uuid)
    client = TestClient(app, follow_redirects=False)
    client.cookies.set("access_token", token)
    return client


# ---------------------------------------------------------------------------
# Unit test 1: State token round-trip (Scenario: state token round-trips)
# ---------------------------------------------------------------------------


def test_state_token_round_trip():
    """
    Scenario: state token round-trips.

    Given a state token generated by create_slack_state_token(user_id="alice-uuid")
    When verify_slack_state_token() is called on it
    Then it returns SlackInstallState(user_id="alice-uuid", exp=<future int>)

    RED PHASE: fails with ImportError until create_slack_state_token,
    verify_slack_state_token, and SlackInstallState exist in Green phase.
    """
    token = create_slack_state_token("alice-uuid")
    state = verify_slack_state_token(token)

    assert isinstance(state, SlackInstallState)
    assert state.user_id == "alice-uuid"

    # exp must be in the future (token has a 300-second window)
    now = int(time.time())
    assert state.exp > now
    # exp should be approximately now + 300 (allow ±10s tolerance)
    assert abs(state.exp - (now + 300)) < 10


# ---------------------------------------------------------------------------
# Unit test 2: State token expiry (Scenario: state token expires after 5 minutes)
# ---------------------------------------------------------------------------


def test_state_token_expiry():
    """
    Scenario: state token expires after 5 minutes.

    Given a state token with iat = now - 301 seconds (1 second past the 300s window)
    When verify_slack_state_token() is called on it
    Then it raises jwt.ExpiredSignatureError

    Uses the now= keyword argument on create_slack_state_token per spec §3.3.
    Does NOT use freezegun — passes a pre-shifted timestamp directly.

    RED PHASE: fails with ImportError until Green phase.
    """
    # Shift iat 301 seconds into the past so exp = past_iat + 300 is already expired
    past_iat = int(time.time()) - 301
    token = create_slack_state_token("alice-uuid", now=past_iat)

    with pytest.raises(jwt.ExpiredSignatureError):
        verify_slack_state_token(token)


# ---------------------------------------------------------------------------
# Unit test 3: State token tamper (Scenario: state token tamper detection)
# ---------------------------------------------------------------------------


def test_state_token_tamper():
    """
    Scenario: state token tamper detection.

    Given a valid state token with one character of the signature segment flipped
    When verify_slack_state_token() is called
    Then it raises jwt.InvalidTokenError (or a subclass: DecodeError, InvalidSignatureError)

    Splits on '.' and mutates the last character of the third segment — the
    same technique as test_security.py::test_decode_token_rejects_tampered_signature.

    RED PHASE: fails with ImportError until Green phase.
    """
    token = create_slack_state_token("alice-uuid")
    head, body, sig = token.split(".")
    # Flip the last character of the signature
    flipped = "A" if sig[-1] != "A" else "B"
    tampered = f"{head}.{body}.{sig[:-1]}{flipped}"

    with pytest.raises(jwt.InvalidTokenError):
        verify_slack_state_token(tampered)


# ---------------------------------------------------------------------------
# Integration test 4: Authenticated 307 (Scenario: authenticated user is redirected)
# ---------------------------------------------------------------------------


def test_authenticated_user_gets_307_redirect(authenticated_client):
    """
    Scenario: authenticated user is redirected to Slack.

    Given user is logged in (access_token cookie set)
    When GET /api/slack/install
    Then the response status is 307
    And the Location header starts with "https://slack.com/oauth/v2/authorize?"
    And query params include: client_id, redirect_uri, scope (all 7), state (non-empty)

    RED PHASE: fails with 404 until slack_oauth router is registered in main.py.
    """
    response = authenticated_client.get("/api/slack/install")

    assert response.status_code == 307, (
        f"Expected 307, got {response.status_code}. "
        "Route may not be registered — check main.py include_router call."
    )

    location = response.headers["location"]
    assert location.startswith("https://slack.com/oauth/v2/authorize?"), (
        f"Location header should point to Slack authorize endpoint, got: {location}"
    )

    # Parse query string
    parsed = urlparse(location)
    qs = parse_qs(parsed.query)

    # client_id must match settings
    assert qs.get("client_id") == [settings.slack_client_id], (
        f"client_id mismatch. Expected [{settings.slack_client_id}], got {qs.get('client_id')}"
    )

    # redirect_uri must match settings
    assert qs.get("redirect_uri") == [settings.slack_redirect_url], (
        f"redirect_uri mismatch. Expected [{settings.slack_redirect_url}], "
        f"got {qs.get('redirect_uri')}"
    )

    # scope must contain all 7 required scopes
    raw_scope = qs.get("scope", [""])[0]
    actual_scopes = set(raw_scope.split(","))
    missing = EXPECTED_SCOPES - actual_scopes
    assert not missing, (
        f"Scope is missing required values: {missing}. Got: {actual_scopes}"
    )

    # state must be non-empty
    state = qs.get("state", [""])[0]
    assert state, "state query parameter must be non-empty (JWT-signed state token)"


# ---------------------------------------------------------------------------
# Integration test 5: Anonymous → 401 (Scenario: anonymous user → 401)
# ---------------------------------------------------------------------------


def test_anonymous_user_gets_401(client):
    """
    Scenario: anonymous user → 401.

    Given no auth cookie
    When GET /api/slack/install
    Then the response status is 401

    The get_current_user_id dependency raises HTTPException(401) when no
    access_token cookie or Authorization header is present.

    RED PHASE: fails with 404 until slack_oauth router is registered.
    """
    response = client.get("/api/slack/install")
    assert response.status_code == 401, (
        f"Expected 401 for anonymous request, got {response.status_code}"
    )


# ---------------------------------------------------------------------------
# Integration test 6: No plaintext user_id in Location header
# ---------------------------------------------------------------------------


def test_location_header_does_not_contain_plaintext_user_id(authenticated_client):
    """
    Scenario: Location header does NOT contain plaintext user_id.

    Given an authenticated user with id containing "alice-uuid-fixture"
    When GET /api/slack/install returns a 307
    Then the Location header does NOT contain the literal string "alice-uuid-fixture"

    The state parameter should be a JWT-signed opaque token, not a raw user_id.
    This test guards against accidentally embedding the user_id in plaintext in
    the redirect URL (e.g., as a state=alice-uuid-fixture query param).

    The authenticated_client fixture uses UUID a11ce000-f1x7-0000-0000-a11ce0fixture
    which contains "a11ce0fixture" — we assert neither this nor "alice-uuid-fixture"
    (the user_id string form) appears literally in the Location header.

    RED PHASE: fails with 404 until slack_oauth router is registered.
    """
    # Use a recognizable user_id that would be obvious if leaked
    recognizable_id = "alice-uuid-fixture"

    # Create a token for a user whose sub claim contains the recognizable string
    # We inject via a fresh client with a manually constructed access token
    # using jwt.encode directly to set a recognizable sub claim
    import jwt as jwt_module
    payload = {
        "sub": recognizable_id,
        "role": "authenticated",
        "iat": int(time.time()),
        "exp": int(time.time()) + 900,
    }
    token = jwt_module.encode(
        payload, settings.supabase_jwt_secret, algorithm=settings.jwt_algorithm
    )

    fresh_client = TestClient(app, follow_redirects=False)
    fresh_client.cookies.set("access_token", token)

    response = fresh_client.get("/api/slack/install")

    assert response.status_code == 307, (
        f"Expected 307 but got {response.status_code} — route may not be registered"
    )

    location = response.headers["location"]
    assert recognizable_id not in location, (
        f"Plaintext user_id '{recognizable_id}' found in Location header: {location}. "
        "The state must be JWT-encoded, not a raw user_id."
    )
