#!/usr/bin/env node

/**
 * vdoc_staleness.mjs
 * Cross-references Dev Reports' files_modified against vdoc manifest key files.
 * Generates a targeted Scribe task file listing stale docs.
 *
 * Usage:
 *   ./.vbounce/scripts/vdoc_staleness.mjs S-05
 *
 * Output: .vbounce/scribe-task-S-05.md
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import yaml from 'js-yaml';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '../..');

const sprintId = process.argv[2];
if (!sprintId) {
  console.error('Usage: vdoc_staleness.mjs S-XX');
  process.exit(1);
}

const VDOCS_DIR = path.join(ROOT, 'vdocs');
const MANIFEST_PATH = path.join(VDOCS_DIR, '_manifest.json');

// ── Check manifest ────────────────────────────────────────────────

if (!fs.existsSync(MANIFEST_PATH)) {
  console.log('No vdocs/_manifest.json found — skipping staleness check');
  process.exit(0);
}

const manifest = JSON.parse(fs.readFileSync(MANIFEST_PATH, 'utf8'));
const docs = manifest.documentation || [];

// ── Collect all files_modified from Dev Reports ───────────────────

const allModifiedFiles = new Set();
const storyModifications = {}; // storyId -> files

function findDevReports(dir) {
  if (!fs.existsSync(dir)) return [];
  const results = [];
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const e of entries) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) results.push(...findDevReports(full));
    else if (e.name.endsWith('-dev.md')) results.push(full);
  }
  return results;
}

const reportDirs = [
  path.join(ROOT, '.vbounce', 'reports'),
  path.join(ROOT, '.vbounce', 'archive', sprintId),
];

for (const dir of reportDirs) {
  const reports = findDevReports(dir);
  for (const report of reports) {
    try {
      const content = fs.readFileSync(report, 'utf8');
      const fmMatch = content.match(/^---\s*\n([\s\S]*?)\n---/);
      if (!fmMatch) continue;
      const fm = yaml.load(fmMatch[1]) || {};
      const files = fm.files_modified || [];
      const storyMatch = path.basename(report).match(/STORY-[\w-]+/);
      const storyId = storyMatch ? storyMatch[0] : 'unknown';
      storyModifications[storyId] = files;
      files.forEach(f => allModifiedFiles.add(f));
    } catch { /* skip malformed reports */ }
  }
}

if (allModifiedFiles.size === 0) {
  console.log('No files_modified found in Dev Reports — nothing to check');
  process.exit(0);
}

// ── Cross-reference against manifest key files ────────────────────

const staleDocs = [];

for (const doc of docs) {
  // Get key files from doc frontmatter or Key Files section
  const docKeyFiles = [];

  // From manifest entry
  if (doc.keyFiles) docKeyFiles.push(...doc.keyFiles);

  // From the doc file itself
  const docPath = path.join(VDOCS_DIR, doc.filepath);
  if (fs.existsSync(docPath)) {
    const content = fs.readFileSync(docPath, 'utf8');

    // Parse frontmatter keyFiles
    const fmMatch = content.match(/^---\s*\n([\s\S]*?)\n---/);
    if (fmMatch) {
      try {
        const fm = yaml.load(fmMatch[1]) || {};
        if (fm.keyFiles) docKeyFiles.push(...fm.keyFiles);
      } catch { /* ignore */ }
    }

    // Parse Key Files table
    const tableMatch = content.match(/## Key Files[\s\S]*?\|[^|]+\|[^|]+\|[^|]+\|([\s\S]*?)(?=\n---|\n##)/);
    if (tableMatch) {
      const rows = tableMatch[1].split('\n').filter(r => r.includes('|'));
      for (const row of rows) {
        const cells = row.split('|').map(c => c.trim());
        const filePath = cells[1]?.replace(/`/g, '');
        if (filePath && filePath.includes('/')) docKeyFiles.push(filePath);
      }
    }
  }

  // Check for overlap
  const uniqueKeyFiles = [...new Set(docKeyFiles)];
  const overlapping = uniqueKeyFiles.filter(kf =>
    [...allModifiedFiles].some(mf => mf.includes(kf) || kf.includes(mf))
  );

  if (overlapping.length > 0) {
    // Find which stories touched these files
    const touchedBy = [];
    for (const [sid, files] of Object.entries(storyModifications)) {
      if (files.some(f => overlapping.some(o => f.includes(o) || o.includes(f)))) {
        touchedBy.push(sid);
      }
    }

    staleDocs.push({
      filepath: doc.filepath,
      title: doc.title,
      overlappingFiles: overlapping,
      touchedBy,
    });
  }
}

if (staleDocs.length === 0) {
  console.log('✓ No stale vdocs detected — all docs are current');
  process.exit(0);
}

// ── Generate Scribe task file ─────────────────────────────────────

const taskLines = [
  `---`,
  `sprint_id: "${sprintId}"`,
  `mode: "audit"`,
  `stale_docs: ${staleDocs.length}`,
  `generated: "${new Date().toISOString().split('T')[0]}"`,
  `---`,
  ``,
  `# Scribe Task: ${sprintId} — Targeted Doc Update`,
  ``,
  `> Auto-generated by staleness detection. ${staleDocs.length} doc(s) need updating.`,
  ``,
  `## Stale Documents`,
  ``,
  `| Doc | Title | Files Modified | Touched By |`,
  `|-----|-------|---------------|------------|`,
  ...staleDocs.map(d =>
    `| ${d.filepath} | ${d.title} | ${d.overlappingFiles.slice(0, 3).join(', ')}${d.overlappingFiles.length > 3 ? ` (+${d.overlappingFiles.length - 3})` : ''} | ${d.touchedBy.join(', ')} |`
  ),
  ``,
  `## Instructions`,
  ``,
  `For each stale doc:`,
  `1. Read the current doc and the Dev Reports from the stories listed above`,
  `2. Re-read the modified source files to understand what changed`,
  `3. Update only the affected sections — do not rewrite the entire doc`,
  `4. Bump frontmatter \`version\` (increment by 1) and set \`lastUpdated\` to today`,
  `5. Update the manifest entry if tags or description need adjustment`,
  `6. Regenerate the context slice in \`vdocs/_slices/\``,
  ``,
  `## Priority`,
  ``,
  ...staleDocs.map(d => {
    const fileCount = d.overlappingFiles.length;
    const priority = fileCount >= 3 ? 'HIGH' : fileCount >= 2 ? 'MEDIUM' : 'LOW';
    return `- **${d.filepath}**: ${priority} (${fileCount} key file(s) modified)`;
  }),
];

const taskFile = path.join(ROOT, '.vbounce', `scribe-task-${sprintId}.md`);
fs.writeFileSync(taskFile, taskLines.join('\n'));

console.log(`✓ Scribe task written to .vbounce/scribe-task-${sprintId}.md`);
console.log(`  ${staleDocs.length} stale doc(s) detected:`);
for (const d of staleDocs) {
  console.log(`  - ${d.filepath} (${d.overlappingFiles.length} key files modified by ${d.touchedBy.join(', ')})`);
}
