import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { RouterProvider, createRouter } from '@tanstack/react-router';

// Design system CSS — must import before any components to ensure @theme tokens
// and @fontsource fonts are loaded globally. See src/app.css for all tokens.
import './app.css';

import { routeTree } from './routeTree.gen';

/**
 * Application router instance.
 *
 * TanStack Router is configured with the auto-generated routeTree from
 * src/routes/ (generated by the TanStackRouterVite plugin at dev/build time).
 * The module augmentation below enables full type-safety on useNavigate,
 * Link, etc. across the entire app.
 */
const router = createRouter({ routeTree });

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}

const rootElement = document.getElementById('root');
if (!rootElement) {
  throw new Error('Root element #root not found — check index.html');
}

createRoot(rootElement).render(
  <StrictMode>
    <RouterProvider router={router} />
  </StrictMode>,
);
