/* eslint-disable */

// This file is auto-generated by @tanstack/router-plugin when running
// `vite dev` or `vite build`. The TanStackRouterVite plugin in vite.config.ts
// watches src/routes/ and regenerates this file on every route change.
//
// For initial scaffold (before npm install + npm run dev), this hand-rolled
// equivalent satisfies TypeScript so the project compiles.
// Running `npm run dev` will overwrite this with the fully typed version.

import { createRootRoute, createRoute, createRouter } from '@tanstack/react-router';

import { Route as rootRoute } from './routes/__root';
import { Route as IndexRoute } from './routes/index';

/**
 * Route tree connecting root and index routes.
 * The TanStackRouterVite plugin replaces this with a fully typed, codegen'd
 * version at dev/build time.
 */
const routeTree = rootRoute.addChildren([IndexRoute]);

export { routeTree };
